apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: gcr.io/k8s-hello-world-312614/hello-app:v1
        ports:
        - containerPort: 3000

